# Generated by Django 3.1.4 on 2021-03-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_campingspot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
